---
abstract: 'Formatting for various spreadsheet readers'
author:
  - 'Jed Lund <jandrew@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '7.04'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.043, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: p5-spreadsheet-reader-format
provides:
  Spreadsheet::Reader::Format:
    file: lib/Spreadsheet/Reader/Format.pm
    version: v0.11.0
  Spreadsheet::Reader::Format::FmtDefault:
    file: lib/Spreadsheet/Reader/Format/FmtDefault.pm
    version: v0.11.0
  Spreadsheet::Reader::Format::ParseExcelFormatStrings:
    file: lib/Spreadsheet/Reader/Format/ParseExcelFormatStrings.pm
    version: v0.11.0
  Spreadsheet::Reader::Format::Types:
    file: lib/Spreadsheet/Reader/Format/Types.pm
    version: v0.11.0
resources:
  bugtracker: https://github.com/jandrew/p5-spreadsheet-reader-format/issues
  homepage: https://github.com/jandrew/p5-spreadsheet-reader-format
  repository: https://github.com/jandrew/p5-spreadsheet-reader-format.git
version: v0.1_1
x_authority: cpan:JANDREW
