---
abstract: 'Formatting for various spreadsheet readers'
author:
  - 'Jed Lund <jandrew@cpan.org>'
build_requires:
  Capture::Tiny: '0'
  Data::Dumper: '0'
  MooseX::ShortCut::BuildInstance: v1.8.0
  Test::Moose: '2.1801'
  Test::Most: '0'
  Test::TypeTiny: '0'
configure_requires:
  ExtUtils::MakeMaker: '7.04'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.005, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Spreadsheet-Reader-Format
provides:
  Spreadsheet::Reader::Format:
    file: lib/Spreadsheet/Reader/Format.pm
    version: v0.6.4
  Spreadsheet::Reader::Format::FmtDefault:
    file: lib/Spreadsheet/Reader/Format/FmtDefault.pm
    version: v0.6.4
  Spreadsheet::Reader::Format::ParseExcelFormatStrings:
    file: lib/Spreadsheet/Reader/Format/ParseExcelFormatStrings.pm
    version: v0.6.4
  Spreadsheet::Reader::Format::Types:
    file: lib/Spreadsheet/Reader/Format/Types.pm
    version: v0.6.4
requires:
  Carp: '0'
  Clone: '0'
  DateTime: '0'
  DateTime::Format::Flexible: '0'
  DateTime::TimeZone: '2.09'
  DateTimeX::Format::Excel: '0.014'
  Encode: '0'
  IO::File: '0'
  Moose: '0'
  Moose::Role: '0'
  Test::Exception: '0.43'
  Test::Moose: '2.1801'
  Type::Coercion: '0'
  Type::Library: '1.000'
  Type::Tiny: '0'
  Type::Utils: '0'
  Types::Standard: '0'
  lib: '0'
  perl: '5.010'
  strict: '0'
  version: '0.77'
  warnings: '0'
resources:
  bugtracker: https://github.com/jandrew/p5-spreadsheet-reader-format/issues
  homepage: https://github.com/jandrew/p5-spreadsheet-reader-format
  repository: https://github.com/jandrew/p5-spreadsheet-reader-format.git
version: v0.6.4
x_authority: cpan:JANDREW
